theme = "dark_high_contrast"

[editor]
scroll-lines = 1
#cursorline = true
auto-save = false
completion-trigger-len = 1
true-color = true
color-modes = true
auto-pairs = true
#rulers = [120]
idle-timeout = 50
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # "┊" # "╎" # "▏"
skip-levels = 1

[editor.lsp]
auto-signature-help = false   # Disable automatically popups of signature parameter help
display-messages = true       # Show LSP messages in the status line
#display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-type", "total-line-numbers", "file-encoding"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]
